// src/plantDatabase.js
export const plantDatabase = {
  // Roses
  "roses": {
    id: "local_roses",
    name: "Rose",
    scientific_name: "Rosa spp.",
    family: "Rosaceae",
    image: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=400",
    description: "Roses are woody perennial flowering plants known for their beautiful blooms and fragrance. They come in many colors and varieties.",
    type: "Perennial",
    cycle: "Perennial",
    watering: "Average",
    sunlight: "Full sun",
    care_level: "Medium",
    growth_rate: "Medium",
    flowering_season: "Spring, Summer, Fall",
    attracts: "Bees, Butterflies",
    maintenance: "Medium",
    deer_resistance: "C",
    deer_resistance_note: "Occasionally severely damaged"
  },

  // Groundcover Juniper
  "groundcover juniper": {
    id: "local_juniper",
    name: "Groundcover Juniper",
    scientific_name: "Juniperus horizontalis",
    family: "Cupressaceae",
    image: "https://images.unsplash.com/photo-1598256989800-fe5f95da9787?w=400",
    description: "A low-growing evergreen shrub perfect for groundcover. Drought-tolerant and requires minimal maintenance.",
    type: "Shrub",
    cycle: "Perennial",
    watering: "Minimum",
    sunlight: "Full sun, Part shade",
    care_level: "Low",
    growth_rate: "Slow",
    flowering_season: "None",
    attracts: "Birds",
    maintenance: "Low",
    deer_resistance: "A",
    deer_resistance_note: "Rarely damaged"
  },

  // Hosta
  "hosta": {
    id: "local_hosta",
    name: "Hosta",
    scientific_name: "Hosta spp.",
    family: "Asparagaceae",
    image: "https://images.unsplash.com/photo-1591958911259-bee2173bdccc?w=400",
    description: "Shade-loving perennial known for its attractive foliage. Hostas come in various sizes with leaves in shades of green, blue, and variegated patterns.",
    type: "Perennial",
    cycle: "Perennial",
    watering: "Average",
    sunlight: "Part shade, Full shade",
    care_level: "Low",
    growth_rate: "Medium",
    flowering_season: "Summer",
    attracts: "Hummingbirds",
    maintenance: "Low",
    deer_resistance: "D",
    deer_resistance_note: "Frequently severely damaged - deer candy!"
  },

  // Hydrangea
  "hydrangea": {
    id: "local_hydrangea",
    name: "Hydrangea",
    scientific_name: "Hydrangea macrophylla",
    family: "Hydrangeaceae",
    image: "https://images.unsplash.com/photo-1595608293560-c7a8d0d5e4e8?w=400",
    description: "Popular flowering shrub with large, showy flower clusters. Flower color can change based on soil pH.",
    type: "Shrub",
    cycle: "Perennial",
    watering: "Frequent",
    sunlight: "Part shade",
    care_level: "Medium",
    growth_rate: "Medium",
    flowering_season: "Summer, Fall",
    attracts: "Butterflies",
    maintenance: "Medium",
    deer_resistance: "B",
    deer_resistance_note: "Seldom severely damaged"
  },

  // Azalea
  "azalea": {
    id: "local_azalea",
    name: "Azalea",
    scientific_name: "Rhododendron spp.",
    family: "Ericaceae",
    image: "https://images.unsplash.com/photo-1617791160505-6f00504e3519?w=400",
    description: "Flowering shrub that produces masses of colorful blooms in spring. Prefers acidic soil.",
    type: "Shrub",
    cycle: "Perennial",
    watering: "Average",
    sunlight: "Part shade",
    care_level: "Medium",
    growth_rate: "Slow",
    flowering_season: "Spring",
    attracts: "Bees, Butterflies, Hummingbirds",
    maintenance: "Medium",
    deer_resistance: "A",
    deer_resistance_note: "Rarely damaged"
  },

  // Weigela
  "weigela": {
    id: "local_weigela",
    name: "Weigela",
    scientific_name: "Weigela florida",
    family: "Caprifoliaceae",
    image: "https://images.unsplash.com/photo-1595845751052-2e1e1d4e2a1e?w=400",
    description: "Deciduous shrub with tubular flowers that bloom profusely in late spring. Attracts hummingbirds.",
    type: "Shrub",
    cycle: "Perennial",
    watering: "Average",
    sunlight: "Full sun, Part shade",
    care_level: "Low",
    growth_rate: "Fast",
    flowering_season: "Spring, Summer",
    attracts: "Hummingbirds, Butterflies",
    maintenance: "Low",
    deer_resistance: "B",
    deer_resistance_note: "Seldom severely damaged"
  },

  // Ninebark
  "ninebark": {
    id: "local_ninebark",
    name: "Ninebark",
    scientific_name: "Physocarpus opulifolius",
    family: "Rosaceae",
    image: "https://images.unsplash.com/photo-1625912098935-69c3c8b3d9f5?w=400",
    description: "Hardy native shrub with attractive foliage and exfoliating bark. Very low maintenance and adaptable.",
    type: "Shrub",
    cycle: "Perennial",
    watering: "Minimum",
    sunlight: "Full sun, Part shade",
    care_level: "Low",
    growth_rate: "Fast",
    flowering_season: "Spring, Summer",
    attracts: "Bees, Butterflies, Birds",
    maintenance: "Low",
    deer_resistance: "B",
    deer_resistance_note: "Seldom severely damaged"
  },

  // Butterfly Bush
  "butterfly bush": {
    id: "local_butterfly_bush",
    name: "Butterfly Bush",
    scientific_name: "Buddleja davidii",
    family: "Scrophulariaceae",
    image: "https://images.unsplash.com/photo-1597868165956-03a6827955b1?w=400",
    description: "Fast-growing deciduous shrub known for attracting butterflies and other pollinators. Produces fragrant flower spikes.",
    type: "Shrub",
    cycle: "Perennial",
    watering: "Minimum",
    sunlight: "Full sun",
    care_level: "Low",
    growth_rate: "Fast",
    flowering_season: "Summer, Fall",
    attracts: "Butterflies, Bees, Hummingbirds",
    maintenance: "Low",
    deer_resistance: "A",
    deer_resistance_note: "Rarely damaged"
  },

  // Common additional plants people might search for:
  
  "tomato": {
    id: "local_tomato",
    name: "Tomato",
    scientific_name: "Solanum lycopersicum",
    family: "Solanaceae",
    image: "https://images.unsplash.com/photo-1592841200221-a6898f307baa?w=400",
    description: "Popular vegetable garden plant producing edible fruits. Requires warm weather and full sun.",
    type: "Annual",
    cycle: "Annual",
    watering: "Average",
    sunlight: "Full sun",
    care_level: "Medium",
    growth_rate: "Fast",
    flowering_season: "Summer",
    attracts: "Bees",
    maintenance: "Medium",
    deer_resistance: "C",
    deer_resistance_note: "Occasionally severely damaged"
  },

  "lavender": {
    id: "local_lavender",
    name: "Lavender",
    scientific_name: "Lavandula angustifolia",
    family: "Lamiaceae",
    image: "https://images.unsplash.com/photo-1595814432314-90095f342694?w=400",
    description: "Aromatic perennial herb with purple flower spikes. Drought-tolerant and attracts pollinators.",
    type: "Perennial",
    cycle: "Perennial",
    watering: "Minimum",
    sunlight: "Full sun",
    care_level: "Low",
    growth_rate: "Medium",
    flowering_season: "Summer",
    attracts: "Bees, Butterflies",
    maintenance: "Low",
    deer_resistance: "A",
    deer_resistance_note: "Rarely damaged - deer don't like the scent"
  },

  "basil": {
    id: "local_basil",
    name: "Basil",
    scientific_name: "Ocimum basilicum",
    family: "Lamiaceae",
    image: "https://images.unsplash.com/photo-1618375569909-3c8616cf727d?w=400",
    description: "Popular culinary herb with aromatic leaves. Easy to grow in warm weather.",
    type: "Annual",
    cycle: "Annual",
    watering: "Average",
    sunlight: "Full sun",
    care_level: "Low",
    growth_rate: "Fast",
    flowering_season: "Summer",
    attracts: "Bees",
    maintenance: "Low",
    deer_resistance: "A",
    deer_resistance_note: "Rarely damaged - aromatic herbs repel deer"
  },

  "maple": {
    id: "local_maple",
    name: "Maple Tree",
    scientific_name: "Acer spp.",
    family: "Sapindaceae",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400",
    description: "Deciduous tree known for brilliant fall foliage. Many species available in various sizes.",
    type: "Tree",
    cycle: "Perennial",
    watering: "Average",
    sunlight: "Full sun, Part shade",
    care_level: "Low",
    growth_rate: "Medium",
    flowering_season: "Spring",
    attracts: "Birds, Squirrels",
    maintenance: "Low",
    deer_resistance: "B",
    deer_resistance_note: "Seldom severely damaged"
  },

  // New additions below

  "azaleas": {
    id: "local_azaleas",
    name: "Azalea",
    scientific_name: "Rhododendron spp.",
    family: "Ericaceae",
    image: "https://images.unsplash.com/photo-1617791160505-6f00504e3519?w=400",
    description: "Flowering shrub that produces masses of colorful blooms in spring. Prefers acidic soil.",
    type: "Shrub",
    cycle: "Perennial",
    watering: "Average",
    sunlight: "Part shade",
    care_level: "Medium",
    growth_rate: "Slow",
    flowering_season: "Spring",
    attracts: "Bees, Butterflies, Hummingbirds",
    maintenance: "Medium",
    deer_resistance: "A",
    deer_resistance_note: "Rarely damaged"
  },

  "rose of sharon": {
    id: "local_rose_of_sharon",
    name: "Rose of Sharon",
    scientific_name: "Hibiscus syriacus",
    family: "Malvaceae",
    image: "https://images.unsplash.com/photo-1597868165956-03a6827955b1?w=400",
    description: "Deciduous flowering shrub with large hibiscus-like flowers that bloom in late summer. Very low maintenance.",
    type: "Shrub",
    cycle: "Perennial",
    watering: "Average",
    sunlight: "Full sun, Part shade",
    care_level: "Low",
    growth_rate: "Fast",
    flowering_season: "Summer, Fall",
    attracts: "Butterflies, Hummingbirds",
    maintenance: "Low",
    deer_resistance: "B",
    deer_resistance_note: "Seldom severely damaged"
  },

  "boxwood": {
    id: "local_boxwood",
    name: "Boxwood",
    scientific_name: "Buxus spp.",
    family: "Buxaceae",
    image: "https://images.unsplash.com/photo-1598256989800-fe5f95da9787?w=400",
    description: "Classic evergreen shrub perfect for hedges and topiaries. Dense foliage and slow growth make it ideal for formal gardens.",
    type: "Shrub",
    cycle: "Perennial",
    watering: "Average",
    sunlight: "Full sun, Part shade",
    care_level: "Low",
    growth_rate: "Slow",
    flowering_season: "Spring",
    attracts: "Bees",
    maintenance: "Low",
    deer_resistance: "A",
    deer_resistance_note: "Rarely damaged"
  },

  "viburnum": {
    id: "local_viburnum",
    name: "Viburnum",
    scientific_name: "Viburnum spp.",
    family: "Adoxaceae",
    image: "https://images.unsplash.com/photo-1595845751052-2e1e1d4e2a1e?w=400",
    description: "Versatile shrub with spring flowers, attractive foliage, and colorful berries that attract birds.",
    type: "Shrub",
    cycle: "Perennial",
    watering: "Average",
    sunlight: "Full sun, Part shade",
    care_level: "Low",
    growth_rate: "Medium",
    flowering_season: "Spring",
    attracts: "Birds, Butterflies",
    maintenance: "Low",
    deer_resistance: "B",
    deer_resistance_note: "Seldom severely damaged"
  },

  "japanese maple": {
    id: "local_japanese_maple",
    name: "Japanese Maple",
    scientific_name: "Acer palmatum",
    family: "Sapindaceae",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400",
    description: "Elegant small tree with delicate, often colorful foliage. Many cultivars available with red, purple, or green leaves.",
    type: "Tree",
    cycle: "Perennial",
    watering: "Average",
    sunlight: "Part shade, Full sun",
    care_level: "Medium",
    growth_rate: "Slow",
    flowering_season: "Spring",
    attracts: "Birds",
    maintenance: "Low",
    deer_resistance: "C",
    deer_resistance_note: "Occasionally severely damaged"
  },

  "spirea": {
    id: "local_spirea",
    name: "Spirea",
    scientific_name: "Spiraea spp.",
    family: "Rosaceae",
    image: "https://images.unsplash.com/photo-1595845751052-2e1e1d4e2a1e?w=400",
    description: "Deciduous flowering shrub with clusters of small flowers. Very hardy and low maintenance.",
    type: "Shrub",
    cycle: "Perennial",
    watering: "Average",
    sunlight: "Full sun, Part shade",
    care_level: "Low",
    growth_rate: "Fast",
    flowering_season: "Spring, Summer",
    attracts: "Butterflies, Bees",
    maintenance: "Low",
    deer_resistance: "B",
    deer_resistance_note: "Seldom severely damaged"
  },

  "barberry": {
    id: "local_barberry",
    name: "Barberry",
    scientific_name: "Berberis spp.",
    family: "Berberidaceae",
    image: "https://images.unsplash.com/photo-1598256989800-fe5f95da9787?w=400",
    description: "Thorny shrub with colorful foliage ranging from green to deep purple. Very deer resistant due to thorns.",
    type: "Shrub",
    cycle: "Perennial",
    watering: "Minimum",
    sunlight: "Full sun, Part shade",
    care_level: "Low",
    growth_rate: "Medium",
    flowering_season: "Spring",
    attracts: "Birds",
    maintenance: "Low",
    deer_resistance: "A",
    deer_resistance_note: "Rarely damaged - thorny"
  },

  "holly": {
    id: "local_holly",
    name: "Holly",
    scientific_name: "Ilex spp.",
    family: "Aquifoliaceae",
    image: "https://images.unsplash.com/photo-1598256989800-fe5f95da9787?w=400",
    description: "Evergreen shrub or tree with glossy leaves and red berries. Many varieties from groundcovers to large trees.",
    type: "Shrub",
    cycle: "Perennial",
    watering: "Average",
    sunlight: "Full sun, Part shade",
    care_level: "Low",
    growth_rate: "Slow",
    flowering_season: "Spring",
    attracts: "Birds",
    maintenance: "Low",
    deer_resistance: "A",
    deer_resistance_note: "Rarely damaged - spiny leaves"
  },

  "dogwood": {
    id: "local_dogwood",
    name: "Dogwood",
    scientific_name: "Cornus florida",
    family: "Cornaceae",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400",
    description: "Native flowering tree with beautiful spring blooms and attractive fall color. Red berries attract birds.",
    type: "Tree",
    cycle: "Perennial",
    watering: "Average",
    sunlight: "Part shade, Full sun",
    care_level: "Medium",
    growth_rate: "Slow",
    flowering_season: "Spring",
    attracts: "Birds, Butterflies",
    maintenance: "Medium",
    deer_resistance: "C",
    deer_resistance_note: "Occasionally severely damaged"
  },

  "magnolia": {
    id: "local_magnolia",
    name: "Magnolia",
    scientific_name: "Magnolia spp.",
    family: "Magnoliaceae",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400",
    description: "Flowering tree with large, showy blooms in spring. Varieties range from small shrubs to large trees.",
    type: "Tree",
    cycle: "Perennial",
    watering: "Average",
    sunlight: "Full sun, Part shade",
    care_level: "Medium",
    growth_rate: "Medium",
    flowering_season: "Spring",
    attracts: "Bees, Birds",
    maintenance: "Low",
    deer_resistance: "B",
    deer_resistance_note: "Seldom severely damaged"
  },

  "redbud": {
    id: "local_redbud",
    name: "Redbud",
    scientific_name: "Cercis canadensis",
    family: "Fabaceae",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400",
    description: "Native small tree with pink-purple flowers covering bare branches in early spring. Heart-shaped leaves.",
    type: "Tree",
    cycle: "Perennial",
    watering: "Average",
    sunlight: "Full sun, Part shade",
    care_level: "Low",
    growth_rate: "Medium",
    flowering_season: "Spring",
    attracts: "Bees, Butterflies",
    maintenance: "Low",
    deer_resistance: "C",
    deer_resistance_note: "Occasionally severely damaged"
  },

  "norway spruce": {
    id: "local_norway_spruce",
    name: "Norway Spruce",
    scientific_name: "Picea abies",
    family: "Pinaceae",
    image: "https://images.unsplash.com/photo-1598256989800-fe5f95da9787?w=400",
    description: "Large evergreen conifer with drooping branches. Fast-growing and makes excellent windbreak or privacy screen.",
    type: "Tree",
    cycle: "Perennial",
    watering: "Minimum",
    sunlight: "Full sun",
    care_level: "Low",
    growth_rate: "Fast",
    flowering_season: "None",
    attracts: "Birds",
    maintenance: "Low",
    deer_resistance: "A",
    deer_resistance_note: "Rarely damaged"
  },

  "green giants": {
    id: "local_green_giants",
    name: "Green Giant Arborvitae",
    scientific_name: "Thuja standishii x plicata",
    family: "Cupressaceae",
    image: "https://images.unsplash.com/photo-1598256989800-fe5f95da9787?w=400",
    description: "Fast-growing evergreen with pyramidal shape. Excellent for privacy screens and windbreaks. Very low maintenance.",
    type: "Tree",
    cycle: "Perennial",
    watering: "Average",
    sunlight: "Full sun, Part shade",
    care_level: "Low",
    growth_rate: "Fast",
    flowering_season: "None",
    attracts: "Birds",
    maintenance: "Low",
    deer_resistance: "A",
    deer_resistance_note: "Rarely damaged"
  },

  "blue spruce": {
    id: "local_blue_spruce",
    name: "Blue Spruce",
    scientific_name: "Picea pungens",
    family: "Pinaceae",
    image: "https://images.unsplash.com/photo-1598256989800-fe5f95da9787?w=400",
    description: "Evergreen conifer with striking blue-gray needles. Stiff, horizontal branches give pyramidal form.",
    type: "Tree",
    cycle: "Perennial",
    watering: "Average",
    sunlight: "Full sun",
    care_level: "Low",
    growth_rate: "Slow",
    flowering_season: "None",
    attracts: "Birds",
    maintenance: "Low",
    deer_resistance: "A",
    deer_resistance_note: "Rarely damaged"
  },

  "juniper": {
    id: "local_juniper",
    name: "Juniper",
    scientific_name: "Juniperus spp.",
    family: "Cupressaceae",
    image: "https://images.unsplash.com/photo-1598256989800-fe5f95da9787?w=400",
    description: "Versatile evergreen available in many forms from groundcovers to upright trees. Very drought tolerant.",
    type: "Shrub",
    cycle: "Perennial",
    watering: "Minimum",
    sunlight: "Full sun",
    care_level: "Low",
    growth_rate: "Slow",
    flowering_season: "None",
    attracts: "Birds",
    maintenance: "Low",
    deer_resistance: "A",
    deer_resistance_note: "Rarely damaged"
  },

  "lirope": {
    id: "local_lirope",
    name: "Liriope",
    scientific_name: "Liriope muscari",
    family: "Asparagaceae",
    image: "https://images.unsplash.com/photo-1591958911259-bee2173bdccc?w=400",
    description: "Evergreen grass-like perennial with purple flower spikes. Excellent groundcover for sun or shade.",
    type: "Perennial",
    cycle: "Perennial",
    watering: "Average",
    sunlight: "Full sun, Part shade, Full shade",
    care_level: "Low",
    growth_rate: "Medium",
    flowering_season: "Summer, Fall",
    attracts: "Bees",
    maintenance: "Low",
    deer_resistance: "A",
    deer_resistance_note: "Rarely damaged"
  },

  "daylily": {
    id: "local_daylily",
    name: "Daylily",
    scientific_name: "Hemerocallis spp.",
    family: "Asphodelaceae",
    image: "https://images.unsplash.com/photo-1591958911259-bee2173bdccc?w=400",
    description: "Hardy perennial with trumpet-shaped flowers. Each flower lasts one day but plants produce many blooms.",
    type: "Perennial",
    cycle: "Perennial",
    watering: "Average",
    sunlight: "Full sun, Part shade",
    care_level: "Low",
    growth_rate: "Fast",
    flowering_season: "Summer",
    attracts: "Butterflies, Hummingbirds",
    maintenance: "Low",
    deer_resistance: "C",
    deer_resistance_note: "Occasionally severely damaged"
  },

  "birch": {
    id: "local_birch",
    name: "Birch",
    scientific_name: "Betula spp.",
    family: "Betulaceae",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400",
    description: "Deciduous tree with distinctive peeling bark. Fast-growing with yellow fall color.",
    type: "Tree",
    cycle: "Perennial",
    watering: "Frequent",
    sunlight: "Full sun",
    care_level: "Medium",
    growth_rate: "Fast",
    flowering_season: "Spring",
    attracts: "Birds",
    maintenance: "Medium",
    deer_resistance: "C",
    deer_resistance_note: "Occasionally severely damaged"
  },

  "lilac": {
    id: "local_lilac",
    name: "Lilac",
    scientific_name: "Syringa vulgaris",
    family: "Oleaceae",
    image: "https://images.unsplash.com/photo-1595845751052-2e1e1d4e2a1e?w=400",
    description: "Classic spring-flowering shrub with fragrant purple, pink, or white blooms. Very cold hardy.",
    type: "Shrub",
    cycle: "Perennial",
    watering: "Average",
    sunlight: "Full sun",
    care_level: "Low",
    growth_rate: "Medium",
    flowering_season: "Spring",
    attracts: "Butterflies, Hummingbirds",
    maintenance: "Low",
    deer_resistance: "B",
    deer_resistance_note: "Seldom severely damaged"
  },

  "yucca": {
    id: "local_yucca",
    name: "Yucca",
    scientific_name: "Yucca filamentosa",
    family: "Asparagaceae",
    image: "https://images.unsplash.com/photo-1598256989800-fe5f95da9787?w=400",
    description: "Architectural evergreen perennial with sword-like leaves and tall flower spikes. Very drought tolerant.",
    type: "Perennial",
    cycle: "Perennial",
    watering: "Minimum",
    sunlight: "Full sun",
    care_level: "Low",
    growth_rate: "Slow",
    flowering_season: "Summer",
    attracts: "Hummingbirds",
    maintenance: "Low",
    deer_resistance: "A",
    deer_resistance_note: "Rarely damaged - sharp leaves"
  },

  "caryopteris": {
    id: "local_caryopteris",
    name: "Caryopteris",
    scientific_name: "Caryopteris x clandonensis",
    family: "Lamiaceae",
    image: "https://images.unsplash.com/photo-1595845751052-2e1e1d4e2a1e?w=400",
    description: "Blue Mist Shrub with fragrant blue flowers in late summer. Attracts butterflies and bees. Deer resistant.",
    type: "Shrub",
    cycle: "Perennial",
    watering: "Minimum",
    sunlight: "Full sun",
    care_level: "Low",
    growth_rate: "Medium",
    flowering_season: "Summer, Fall",
    attracts: "Butterflies, Bees",
    maintenance: "Low",
    deer_resistance: "A",
    deer_resistance_note: "Rarely damaged - aromatic"
  },

  "itea": {
    id: "local_itea",
    name: "Sweetspire",
    scientific_name: "Itea virginica",
    family: "Iteaceae",
    image: "https://images.unsplash.com/photo-1595845751052-2e1e1d4e2a1e?w=400",
    description: "Native shrub with fragrant white flower spikes and brilliant red fall color. Tolerates wet soil.",
    type: "Shrub",
    cycle: "Perennial",
    watering: "Average",
    sunlight: "Full sun, Part shade",
    care_level: "Low",
    growth_rate: "Medium",
    flowering_season: "Summer",
    attracts: "Butterflies, Bees",
    maintenance: "Low",
    deer_resistance: "B",
    deer_resistance_note: "Seldom severely damaged"
  },

  "fothergilla": {
    id: "local_fothergilla",
    name: "Fothergilla",
    scientific_name: "Fothergilla gardenii",
    family: "Hamamelidaceae",
    image: "https://images.unsplash.com/photo-1595845751052-2e1e1d4e2a1e?w=400",
    description: "Native shrub with bottlebrush-like white flowers in spring and spectacular fall color. Low maintenance.",
    type: "Shrub",
    cycle: "Perennial",
    watering: "Average",
    sunlight: "Full sun, Part shade",
    care_level: "Low",
    growth_rate: "Slow",
    flowering_season: "Spring",
    attracts: "Bees",
    maintenance: "Low",
    deer_resistance: "A",
    deer_resistance_note: "Rarely damaged"
  },

  "winterberry": {
    id: "local_winterberry",
    name: "Winterberry Holly",
    scientific_name: "Ilex verticillata",
    family: "Aquifoliaceae",
    image: "https://images.unsplash.com/photo-1598256989800-fe5f95da9787?w=400",
    description: "Deciduous holly with brilliant red berries that persist into winter. Excellent for birds.",
    type: "Shrub",
    cycle: "Perennial",
    watering: "Average",
    sunlight: "Full sun, Part shade",
    care_level: "Low",
    growth_rate: "Medium",
    flowering_season: "Spring",
    attracts: "Birds",
    maintenance: "Low",
    deer_resistance: "B",
    deer_resistance_note: "Seldom severely damaged"
  },

  "abelia": {
    id: "local_abelia",
    name: "Abelia",
    scientific_name: "Abelia x grandiflora",
    family: "Caprifoliaceae",
    image: "https://images.unsplash.com/photo-1595845751052-2e1e1d4e2a1e?w=400",
    description: "Semi-evergreen shrub with fragrant white-pink flowers from summer to fall. Very long blooming.",
    type: "Shrub",
    cycle: "Perennial",
    watering: "Average",
    sunlight: "Full sun, Part shade",
    care_level: "Low",
    growth_rate: "Medium",
    flowering_season: "Summer, Fall",
    attracts: "Butterflies, Bees, Hummingbirds",
    maintenance: "Low",
    deer_resistance: "B",
    deer_resistance_note: "Seldom severely damaged"
  },

  "burning bush": {
    id: "local_burning_bush",
    name: "Burning Bush",
    scientific_name: "Euonymus alatus",
    family: "Celastraceae",
    image: "https://images.unsplash.com/photo-1598256989800-fe5f95da9787?w=400",
    description: "Deciduous shrub famous for brilliant red fall color. Dense branching structure.",
    type: "Shrub",
    cycle: "Perennial",
    watering: "Average",
    sunlight: "Full sun, Part shade",
    care_level: "Low",
    growth_rate: "Medium",
    flowering_season: "Spring",
    attracts: "Birds",
    maintenance: "Low",
    deer_resistance: "B",
    deer_resistance_note: "Seldom severely damaged"
  },

  "leucothoe": {
    id: "local_leucothoe",
    name: "Leucothoe",
    scientific_name: "Leucothoe fontanesiana",
    family: "Ericaceae",
    image: "https://images.unsplash.com/photo-1598256989800-fe5f95da9787?w=400",
    description: "Evergreen shrub with arching branches and drooping white flowers. Excellent for shade.",
    type: "Shrub",
    cycle: "Perennial",
    watering: "Average",
    sunlight: "Part shade, Full shade",
    care_level: "Low",
    growth_rate: "Slow",
    flowering_season: "Spring",
    attracts: "Bees",
    maintenance: "Low",
    deer_resistance: "A",
    deer_resistance_note: "Rarely damaged"
  },

  "deutzia": {
    id: "local_deutzia",
    name: "Deutzia",
    scientific_name: "Deutzia gracilis",
    family: "Hydrangeaceae",
    image: "https://images.unsplash.com/photo-1595845751052-2e1e1d4e2a1e?w=400",
    description: "Deciduous shrub with masses of white or pink flowers in spring. Easy to grow.",
    type: "Shrub",
    cycle: "Perennial",
    watering: "Average",
    sunlight: "Full sun, Part shade",
    care_level: "Low",
    growth_rate: "Medium",
    flowering_season: "Spring",
    attracts: "Butterflies, Bees",
    maintenance: "Low",
    deer_resistance: "B",
    deer_resistance_note: "Seldom severely damaged"
  },

  "andromeda": {
    id: "local_andromeda",
    name: "Andromeda",
    scientific_name: "Pieris japonica",
    family: "Ericaceae",
    image: "https://images.unsplash.com/photo-1598256989800-fe5f95da9787?w=400",
    description: "Evergreen shrub with drooping clusters of bell-shaped flowers. New growth is often colorful.",
    type: "Shrub",
    cycle: "Perennial",
    watering: "Average",
    sunlight: "Part shade",
    care_level: "Medium",
    growth_rate: "Slow",
    flowering_season: "Spring",
    attracts: "Bees",
    maintenance: "Medium",
    deer_resistance: "A",
    deer_resistance_note: "Rarely damaged - toxic"
  },

  "clethra": {
    id: "local_clethra",
    name: "Summersweet",
    scientific_name: "Clethra alnifolia",
    family: "Clethraceae",
    image: "https://images.unsplash.com/photo-1595845751052-2e1e1d4e2a1e?w=400",
    description: "Native shrub with fragrant white flower spikes in summer. Tolerates wet soil and shade.",
    type: "Shrub",
    cycle: "Perennial",
    watering: "Average",
    sunlight: "Full sun, Part shade",
    care_level: "Low",
    growth_rate: "Medium",
    flowering_season: "Summer",
    attracts: "Butterflies, Bees, Hummingbirds",
    maintenance: "Low",
    deer_resistance: "B",
    deer_resistance_note: "Seldom severely damaged"
  },

  "aronia": {
    id: "local_aronia",
    name: "Chokeberry",
    scientific_name: "Aronia melanocarpa",
    family: "Rosaceae",
    image: "https://images.unsplash.com/photo-1595845751052-2e1e1d4e2a1e?w=400",
    description: "Native shrub with white spring flowers, edible berries, and brilliant fall color. Very adaptable.",
    type: "Shrub",
    cycle: "Perennial",
    watering: "Average",
    sunlight: "Full sun, Part shade",
    care_level: "Low",
    growth_rate: "Medium",
    flowering_season: "Spring",
    attracts: "Birds, Butterflies",
    maintenance: "Low",
    deer_resistance: "B",
    deer_resistance_note: "Seldom severely damaged"
  },

  "calycanthus": {
    id: "local_calycanthus",
    name: "Sweetshrub",
    scientific_name: "Calycanthus floridus",
    family: "Calycanthaceae",
    image: "https://images.unsplash.com/photo-1595845751052-2e1e1d4e2a1e?w=400",
    description: "Native shrub with uniquely fragrant reddish-brown flowers. Aromatic foliage when crushed.",
    type: "Shrub",
    cycle: "Perennial",
    watering: "Average",
    sunlight: "Full sun, Part shade",
    care_level: "Low",
    growth_rate: "Medium",
    flowering_season: "Spring, Summer",
    attracts: "Butterflies",
    maintenance: "Low",
    deer_resistance: "A",
    deer_resistance_note: "Rarely damaged"
  },

  "camellia": {
    id: "local_camellia",
    name: "Camellia",
    scientific_name: "Camellia japonica",
    family: "Theaceae",
    image: "https://images.unsplash.com/photo-1595845751052-2e1e1d4e2a1e?w=400",
    description: "Evergreen shrub with showy flowers in late winter/early spring. Glossy dark green foliage.",
    type: "Shrub",
    cycle: "Perennial",
    watering: "Average",
    sunlight: "Part shade",
    care_level: "Medium",
    growth_rate: "Slow",
    flowering_season: "Winter, Spring",
    attracts: "Bees",
    maintenance: "Medium",
    deer_resistance: "B",
    deer_resistance_note: "Seldom severely damaged"
  },

  "osmanthus": {
    id: "local_osmanthus",
    name: "Osmanthus",
    scientific_name: "Osmanthus heterophyllus",
    family: "Oleaceae",
    image: "https://images.unsplash.com/photo-1598256989800-fe5f95da9787?w=400",
    description: "Evergreen shrub with holly-like leaves and small but intensely fragrant white flowers in fall.",
    type: "Shrub",
    cycle: "Perennial",
    watering: "Average",
    sunlight: "Full sun, Part shade",
    care_level: "Low",
    growth_rate: "Slow",
    flowering_season: "Fall",
    attracts: "Bees",
    maintenance: "Low",
    deer_resistance: "A",
    deer_resistance_note: "Rarely damaged - spiny leaves"
  },

  "spicebush": {
    id: "local_spicebush",
    name: "Spicebush",
    scientific_name: "Lindera benzoin",
    family: "Lauraceae",
    image: "https://images.unsplash.com/photo-1595845751052-2e1e1d4e2a1e?w=400",
    description: "Native shrub with aromatic foliage, small yellow spring flowers, and red berries. Important for butterflies.",
    type: "Shrub",
    cycle: "Perennial",
    watering: "Average",
    sunlight: "Part shade, Full shade",
    care_level: "Low",
    growth_rate: "Medium",
    flowering_season: "Spring",
    attracts: "Birds, Butterflies",
    maintenance: "Low",
    deer_resistance: "A",
    deer_resistance_note: "Rarely damaged - aromatic"
  },

  "witch hazel": {
    id: "local_witch_hazel",
    name: "Witch Hazel",
    scientific_name: "Hamamelis virginiana",
    family: "Hamamelidaceae",
    image: "https://images.unsplash.com/photo-1595845751052-2e1e1d4e2a1e?w=400",
    description: "Native large shrub with unique ribbon-like yellow flowers in late fall. Excellent fall color.",
    type: "Shrub",
    cycle: "Perennial",
    watering: "Average",
    sunlight: "Full sun, Part shade",
    care_level: "Low",
    growth_rate: "Slow",
    flowering_season: "Fall",
    attracts: "Bees",
    maintenance: "Low",
    deer_resistance: "B",
    deer_resistance_note: "Seldom severely damaged"
  },

  "carex": {
    id: "local_carex",
    name: "Sedge",
    scientific_name: "Carex spp.",
    family: "Cyperaceae",
    image: "https://images.unsplash.com/photo-1591958911259-bee2173bdccc?w=400",
    description: "Grass-like perennial excellent for shady areas. Many varieties with different colors and textures.",
    type: "Perennial",
    cycle: "Perennial",
    watering: "Average",
    sunlight: "Part shade, Full shade",
    care_level: "Low",
    growth_rate: "Medium",
    flowering_season: "Spring",
    attracts: "Birds",
    maintenance: "Low",
    deer_resistance: "A",
    deer_resistance_note: "Rarely damaged"
  },

  "vinca": {
    id: "local_vinca",
    name: "Vinca",
    scientific_name: "Vinca minor",
    family: "Apocynaceae",
    image: "https://images.unsplash.com/photo-1591958911259-bee2173bdccc?w=400",
    description: "Evergreen groundcover with blue or white flowers. Excellent for slopes and under trees.",
    type: "Perennial",
    cycle: "Perennial",
    watering: "Average",
    sunlight: "Part shade, Full shade",
    care_level: "Low",
    growth_rate: "Fast",
    flowering_season: "Spring",
    attracts: "Bees",
    maintenance: "Low",
    deer_resistance: "A",
    deer_resistance_note: "Rarely damaged - toxic"
  },

  "beech": {
    id: "local_beech",
    name: "Beech",
    scientific_name: "Fagus spp.",
    family: "Fagaceae",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400",
    description: "Majestic deciduous tree with smooth gray bark and golden fall color. Long-lived specimen tree.",
    type: "Tree",
    cycle: "Perennial",
    watering: "Average",
    sunlight: "Full sun, Part shade",
    care_level: "Low",
    growth_rate: "Slow",
    flowering_season: "Spring",
    attracts: "Birds, Squirrels",
    maintenance: "Low",
    deer_resistance: "C",
    deer_resistance_note: "Occasionally severely damaged"
  },

  "cherry": {
    id: "local_cherry",
    name: "Flowering Cherry",
    scientific_name: "Prunus spp.",
    family: "Rosaceae",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400",
    description: "Ornamental tree with spectacular spring flower display. Pink or white blossoms cover branches.",
    type: "Tree",
    cycle: "Perennial",
    watering: "Average",
    sunlight: "Full sun",
    care_level: "Medium",
    growth_rate: "Medium",
    flowering_season: "Spring",
    attracts: "Bees, Birds",
    maintenance: "Medium",
    deer_resistance: "C",
    deer_resistance_note: "Occasionally severely damaged"
  },

  "pear": {
    id: "local_pear",
    name: "Ornamental Pear",
    scientific_name: "Pyrus calleryana",
    family: "Rosaceae",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400",
    description: "Flowering tree with white spring blooms and excellent fall color. Fast-growing.",
    type: "Tree",
    cycle: "Perennial",
    watering: "Average",
    sunlight: "Full sun",
    care_level: "Low",
    growth_rate: "Fast",
    flowering_season: "Spring",
    attracts: "Bees, Birds",
    maintenance: "Low",
    deer_resistance: "C",
    deer_resistance_note: "Occasionally severely damaged"
  },

  "euonymus": {
    id: "local_euonymus",
    name: "Euonymus",
    scientific_name: "Euonymus spp.",
    family: "Celastraceae",
    image: "https://images.unsplash.com/photo-1598256989800-fe5f95da9787?w=400",
    description: "Versatile evergreen shrub available in many forms. Often has variegated foliage.",
    type: "Shrub",
    cycle: "Perennial",
    watering: "Average",
    sunlight: "Full sun, Part shade",
    care_level: "Low",
    growth_rate: "Medium",
    flowering_season: "Spring",
    attracts: "Birds",
    maintenance: "Low",
    deer_resistance: "B",
    deer_resistance_note: "Seldom severely damaged"
  },

  "schip laurel": {
    id: "local_schip_laurel",
    name: "Schip Laurel",
    scientific_name: "Prunus laurocerasus 'Schipkaensis'",
    family: "Rosaceae",
    image: "https://images.unsplash.com/photo-1598256989800-fe5f95da9787?w=400",
    description: "Evergreen shrub with glossy dark green leaves. Excellent for hedges and privacy screens. Cold hardy variety of Cherry Laurel.",
    type: "Shrub",
    cycle: "Perennial",
    watering: "Average",
    sunlight: "Full sun, Part shade",
    care_level: "Low",
    growth_rate: "Fast",
    flowering_season: "Spring",
    attracts: "Bees, Birds",
    maintenance: "Low",
    deer_resistance: "B",
    deer_resistance_note: "Seldom severely damaged"
  },

  "skip laurel": {
    id: "local_skip_laurel",
    name: "Skip Laurel",
    scientific_name: "Prunus laurocerasus 'Schipkaensis'",
    family: "Rosaceae",
    image: "https://images.unsplash.com/photo-1598256989800-fe5f95da9787?w=400",
    description: "Evergreen shrub with glossy dark green leaves. Excellent for hedges and privacy screens. Cold hardy variety of Cherry Laurel.",
    type: "Shrub",
    cycle: "Perennial",
    watering: "Average",
    sunlight: "Full sun, Part shade",
    care_level: "Low",
    growth_rate: "Fast",
    flowering_season: "Spring",
    attracts: "Bees, Birds",
    maintenance: "Low",
    deer_resistance: "B",
    deer_resistance_note: "Seldom severely damaged"
  },

  "otto luyken": {
    id: "local_otto_luyken",
    name: "Otto Luyken Laurel",
    scientific_name: "Prunus laurocerasus 'Otto Luyken'",
    family: "Rosaceae",
    image: "https://images.unsplash.com/photo-1598256989800-fe5f95da9787?w=400",
    description: "Compact evergreen shrub with narrow dark green leaves and white flower spikes. Excellent low-growing hedge plant.",
    type: "Shrub",
    cycle: "Perennial",
    watering: "Average",
    sunlight: "Full sun, Part shade, Full shade",
    care_level: "Low",
    growth_rate: "Slow",
    flowering_season: "Spring",
    attracts: "Bees, Butterflies",
    maintenance: "Low",
    deer_resistance: "B",
    deer_resistance_note: "Seldom severely damaged"
  },

  "gold mop": {
    id: "local_gold_mop",
    name: "Gold Mop Cypress",
    scientific_name: "Chamaecyparis pisifera 'Gold Mop'",
    family: "Cupressaceae",
    image: "https://images.unsplash.com/photo-1598256989800-fe5f95da9787?w=400",
    description: "Dwarf evergreen with bright golden thread-like foliage. Compact mounding form perfect for accents.",
    type: "Shrub",
    cycle: "Perennial",
    watering: "Average",
    sunlight: "Full sun, Part shade",
    care_level: "Low",
    growth_rate: "Slow",
    flowering_season: "None",
    attracts: "Birds",
    maintenance: "Low",
    deer_resistance: "A",
    deer_resistance_note: "Rarely damaged"
  },

  "red bud": {
    id: "local_red_bud",
    name: "Redbud",
    scientific_name: "Cercis canadensis",
    family: "Fabaceae",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400",
    description: "Native small tree with pink-purple flowers covering bare branches in early spring. Heart-shaped leaves.",
    type: "Tree",
    cycle: "Perennial",
    watering: "Average",
    sunlight: "Full sun, Part shade",
    care_level: "Low",
    growth_rate: "Medium",
    flowering_season: "Spring",
    attracts: "Bees, Butterflies",
    maintenance: "Low",
    deer_resistance: "C",
    deer_resistance_note: "Occasionally severely damaged"
  },

  "nishiki willow": {
    id: "local_nishiki_willow",
    name: "Nishiki Dappled Willow",
    scientific_name: "Salix integra 'Hakuro-nishiki'",
    family: "Salicaceae",
    image: "https://images.unsplash.com/photo-1598256989800-fe5f95da9787?w=400",
    description: "Deciduous shrub with striking pink, white, and green variegated foliage. New growth is especially colorful.",
    type: "Shrub",
    cycle: "Perennial",
    watering: "Frequent",
    sunlight: "Full sun, Part shade",
    care_level: "Low",
    growth_rate: "Fast",
    flowering_season: "Spring",
    attracts: "Bees",
    maintenance: "Medium",
    deer_resistance: "C",
    deer_resistance_note: "Occasionally severely damaged"
  },

  "alberta spruce": {
    id: "local_alberta_spruce",
    name: "Dwarf Alberta Spruce",
    scientific_name: "Picea glauca 'Conica'",
    family: "Pinaceae",
    image: "https://images.unsplash.com/photo-1598256989800-fe5f95da9787?w=400",
    description: "Compact evergreen conifer with perfect pyramidal form. Slow-growing with dense bright green needles.",
    type: "Tree",
    cycle: "Perennial",
    watering: "Average",
    sunlight: "Full sun",
    care_level: "Low",
    growth_rate: "Slow",
    flowering_season: "None",
    attracts: "Birds",
    maintenance: "Low",
    deer_resistance: "A",
    deer_resistance_note: "Rarely damaged"
  },

  "globosa": {
    id: "local_globosa",
    name: "Globe Blue Spruce",
    scientific_name: "Picea pungens 'Globosa'",
    family: "Pinaceae",
    image: "https://images.unsplash.com/photo-1598256989800-fe5f95da9787?w=400",
    description: "Dwarf blue spruce with rounded form. Silvery-blue needles create striking accent plant.",
    type: "Shrub",
    cycle: "Perennial",
    watering: "Average",
    sunlight: "Full sun",
    care_level: "Low",
    growth_rate: "Slow",
    flowering_season: "None",
    attracts: "Birds",
    maintenance: "Low",
    deer_resistance: "A",
    deer_resistance_note: "Rarely damaged"
  },

  "standing ovation blue stem": {
    id: "local_standing_ovation",
    name: "Standing Ovation Little Bluestem",
    scientific_name: "Schizachyrium scoparium 'Standing Ovation'",
    family: "Poaceae",
    image: "https://images.unsplash.com/photo-1591958911259-bee2173bdccc?w=400",
    description: "Ornamental grass with upright blue-green foliage that turns burgundy in fall. Native prairie grass.",
    type: "Perennial",
    cycle: "Perennial",
    watering: "Minimum",
    sunlight: "Full sun",
    care_level: "Low",
    growth_rate: "Medium",
    flowering_season: "Summer, Fall",
    attracts: "Birds",
    maintenance: "Low",
    deer_resistance: "A",
    deer_resistance_note: "Rarely damaged"
  },

  "mexican feather grass": {
    id: "local_mexican_feather_grass",
    name: "Mexican Feather Grass",
    scientific_name: "Nassella tenuissima",
    family: "Poaceae",
    image: "https://images.unsplash.com/photo-1591958911259-bee2173bdccc?w=400",
    description: "Soft, fine-textured ornamental grass with hair-like foliage that moves gracefully in the breeze.",
    type: "Perennial",
    cycle: "Perennial",
    watering: "Minimum",
    sunlight: "Full sun",
    care_level: "Low",
    growth_rate: "Fast",
    flowering_season: "Summer",
    attracts: "Birds",
    maintenance: "Low",
    deer_resistance: "A",
    deer_resistance_note: "Rarely damaged"
  },

  "karl foerster grass": {
    id: "local_karl_foerster",
    name: "Karl Foerster Grass",
    scientific_name: "Calamagrostis x acutiflora 'Karl Foerster'",
    family: "Poaceae",
    image: "https://images.unsplash.com/photo-1591958911259-bee2173bdccc?w=400",
    description: "Upright ornamental grass with wheat-colored plumes. Very reliable and low maintenance.",
    type: "Perennial",
    cycle: "Perennial",
    watering: "Average",
    sunlight: "Full sun, Part shade",
    care_level: "Low",
    growth_rate: "Medium",
    flowering_season: "Summer",
    attracts: "Birds",
    maintenance: "Low",
    deer_resistance: "A",
    deer_resistance_note: "Rarely damaged"
  },

  "miscanthus morning light": {
    id: "local_miscanthus_morning_light",
    name: "Morning Light Maiden Grass",
    scientific_name: "Miscanthus sinensis 'Morning Light'",
    family: "Poaceae",
    image: "https://images.unsplash.com/photo-1591958911259-bee2173bdccc?w=400",
    description: "Elegant ornamental grass with fine white-edged foliage. Coppery plumes in fall.",
    type: "Perennial",
    cycle: "Perennial",
    watering: "Average",
    sunlight: "Full sun",
    care_level: "Low",
    growth_rate: "Medium",
    flowering_season: "Fall",
    attracts: "Birds",
    maintenance: "Low",
    deer_resistance: "A",
    deer_resistance_note: "Rarely damaged"
  },

  "panicum virgatum": {
    id: "local_panicum_virgatum",
    name: "Switchgrass",
    scientific_name: "Panicum virgatum",
    family: "Poaceae",
    image: "https://images.unsplash.com/photo-1591958911259-bee2173bdccc?w=400",
    description: "Native prairie grass with upright form. Blue-green foliage turns golden in fall with airy seed heads.",
    type: "Perennial",
    cycle: "Perennial",
    watering: "Average",
    sunlight: "Full sun",
    care_level: "Low",
    growth_rate: "Fast",
    flowering_season: "Summer, Fall",
    attracts: "Birds",
    maintenance: "Low",
    deer_resistance: "A",
    deer_resistance_note: "Rarely damaged"
  },

  "hameln grass": {
    id: "local_hameln_grass",
    name: "Hameln Fountain Grass",
    scientific_name: "Pennisetum alopecuroides 'Hameln'",
    family: "Poaceae",
    image: "https://images.unsplash.com/photo-1591958911259-bee2173bdccc?w=400",
    description: "Compact ornamental grass with bottlebrush-like plumes. Dark green foliage turns golden in fall.",
    type: "Perennial",
    cycle: "Perennial",
    watering: "Average",
    sunlight: "Full sun",
    care_level: "Low",
    growth_rate: "Medium",
    flowering_season: "Summer, Fall",
    attracts: "Birds",
    maintenance: "Low",
    deer_resistance: "A",
    deer_resistance_note: "Rarely damaged"
  },

  "vinca bowles": {
    id: "local_vinca_bowles",
    name: "Vinca Bowles",
    scientific_name: "Vinca minor 'Bowles'",
    family: "Apocynaceae",
    image: "https://images.unsplash.com/photo-1591958911259-bee2173bdccc?w=400",
    description: "Evergreen groundcover with large blue-purple flowers. Excellent for slopes and shady areas.",
    type: "Perennial",
    cycle: "Perennial",
    watering: "Average",
    sunlight: "Part shade, Full shade",
    care_level: "Low",
    growth_rate: "Fast",
    flowering_season: "Spring",
    attracts: "Bees",
    maintenance: "Low",
    deer_resistance: "A",
    deer_resistance_note: "Rarely damaged - toxic"
  },

  "dwarf japanese white pine": {
    id: "local_dwarf_japanese_white_pine",
    name: "Dwarf Japanese White Pine",
    scientific_name: "Pinus parviflora",
    family: "Pinaceae",
    image: "https://images.unsplash.com/photo-1598256989800-fe5f95da9787?w=400",
    description: "Compact evergreen with soft blue-green needles. Slow-growing with graceful irregular form.",
    type: "Tree",
    cycle: "Perennial",
    watering: "Average",
    sunlight: "Full sun",
    care_level: "Low",
    growth_rate: "Slow",
    flowering_season: "None",
    attracts: "Birds",
    maintenance: "Low",
    deer_resistance: "A",
    deer_resistance_note: "Rarely damaged"
  },

  "oriental spruce": {
    id: "local_oriental_spruce",
    name: "Oriental Spruce",
    scientific_name: "Picea orientalis",
    family: "Pinaceae",
    image: "https://images.unsplash.com/photo-1598256989800-fe5f95da9787?w=400",
    description: "Graceful evergreen conifer with short dark green needles. Pyramidal form with pendulous branches.",
    type: "Tree",
    cycle: "Perennial",
    watering: "Average",
    sunlight: "Full sun",
    care_level: "Low",
    growth_rate: "Slow",
    flowering_season: "None",
    attracts: "Birds",
    maintenance: "Low",
    deer_resistance: "A",
    deer_resistance_note: "Rarely damaged"
  },

  "golden spruce": {
    id: "local_golden_spruce",
    name: "Golden Norway Spruce",
    scientific_name: "Picea abies 'Aurea'",
    family: "Pinaceae",
    image: "https://images.unsplash.com/photo-1598256989800-fe5f95da9787?w=400",
    description: "Evergreen conifer with golden-yellow new growth. Color fades to green by summer.",
    type: "Tree",
    cycle: "Perennial",
    watering: "Average",
    sunlight: "Full sun",
    care_level: "Low",
    growth_rate: "Medium",
    flowering_season: "None",
    attracts: "Birds",
    maintenance: "Low",
    deer_resistance: "A",
    deer_resistance_note: "Rarely damaged"
  },

  "nest spruce": {
    id: "local_nest_spruce",
    name: "Bird's Nest Spruce",
    scientific_name: "Picea abies 'Nidiformis'",
    family: "Pinaceae",
    image: "https://images.unsplash.com/photo-1598256989800-fe5f95da9787?w=400",
    description: "Dwarf evergreen spruce with nest-like depression in center. Compact, flat-topped form.",
    type: "Shrub",
    cycle: "Perennial",
    watering: "Average",
    sunlight: "Full sun, Part shade",
    care_level: "Low",
    growth_rate: "Slow",
    flowering_season: "None",
    attracts: "Birds",
    maintenance: "Low",
    deer_resistance: "A",
    deer_resistance_note: "Rarely damaged"
  },

  "whipcord western red cedar": {
    id: "local_whipcord_cedar",
    name: "Whipcord Western Red Cedar",
    scientific_name: "Thuja plicata 'Whipcord'",
    family: "Cupressaceae",
    image: "https://images.unsplash.com/photo-1598256989800-fe5f95da9787?w=400",
    description: "Unusual dwarf evergreen with drooping cord-like foliage. Slow-growing mounded form.",
    type: "Shrub",
    cycle: "Perennial",
    watering: "Average",
    sunlight: "Full sun, Part shade",
    care_level: "Low",
    growth_rate: "Slow",
    flowering_season: "None",
    attracts: "Birds",
    maintenance: "Low",
    deer_resistance: "A",
    deer_resistance_note: "Rarely damaged"
  },

  "globe thuja rhein gold": {
    id: "local_globe_thuja",
    name: "Rheingold Arborvitae",
    scientific_name: "Thuja occidentalis 'Rheingold'",
    family: "Cupressaceae",
    image: "https://images.unsplash.com/photo-1598256989800-fe5f95da9787?w=400",
    description: "Dwarf evergreen with golden-amber foliage that deepens to copper-orange in winter.",
    type: "Shrub",
    cycle: "Perennial",
    watering: "Average",
    sunlight: "Full sun",
    care_level: "Low",
    growth_rate: "Slow",
    flowering_season: "None",
    attracts: "Birds",
    maintenance: "Low",
    deer_resistance: "B",
    deer_resistance_note: "Seldom severely damaged"
  },

  "deodar cedar": {
    id: "local_deodar_cedar",
    name: "Deodar Cedar",
    scientific_name: "Cedrus deodara",
    family: "Pinaceae",
    image: "https://images.unsplash.com/photo-1598256989800-fe5f95da9787?w=400",
    description: "Graceful evergreen conifer with soft blue-green needles and drooping branch tips. Pyramidal form.",
    type: "Tree",
    cycle: "Perennial",
    watering: "Average",
    sunlight: "Full sun",
    care_level: "Low",
    growth_rate: "Medium",
    flowering_season: "None",
    attracts: "Birds",
    maintenance: "Low",
    deer_resistance: "A",
    deer_resistance_note: "Rarely damaged"
  },

  "plum yew": {
    id: "local_plum_yew",
    name: "Plum Yew",
    scientific_name: "Cephalotaxus harringtonia",
    family: "Taxaceae",
    image: "https://images.unsplash.com/photo-1598256989800-fe5f95da9787?w=400",
    description: "Evergreen shrub with dark green needle-like foliage. Excellent for shade, very deer resistant.",
    type: "Shrub",
    cycle: "Perennial",
    watering: "Average",
    sunlight: "Part shade, Full shade",
    care_level: "Low",
    growth_rate: "Slow",
    flowering_season: "None",
    attracts: "Birds",
    maintenance: "Low",
    deer_resistance: "A",
    deer_resistance_note: "Rarely damaged - toxic"
  },

  "cryptomeria globe": {
    id: "local_cryptomeria_globe",
    name: "Globe Cryptomeria",
    scientific_name: "Cryptomeria japonica 'Globosa Nana'",
    family: "Cupressaceae",
    image: "https://images.unsplash.com/photo-1598256989800-fe5f95da9787?w=400",
    description: "Dwarf evergreen with dense rounded form. Green foliage turns bronze-purple in winter.",
    type: "Shrub",
    cycle: "Perennial",
    watering: "Average",
    sunlight: "Full sun, Part shade",
    care_level: "Low",
    growth_rate: "Slow",
    flowering_season: "None",
    attracts: "Birds",
    maintenance: "Low",
    deer_resistance: "A",
    deer_resistance_note: "Rarely damaged"
  },

  "dwarf mugo pine": {
    id: "local_dwarf_mugo_pine",
    name: "Dwarf Mugo Pine",
    scientific_name: "Pinus mugo var. pumilio",
    family: "Pinaceae",
    image: "https://images.unsplash.com/photo-1598256989800-fe5f95da9787?w=400",
    description: "Compact evergreen with dark green needles. Dense rounded form, excellent for foundation plantings.",
    type: "Shrub",
    cycle: "Perennial",
    watering: "Minimum",
    sunlight: "Full sun",
    care_level: "Low",
    growth_rate: "Slow",
    flowering_season: "None",
    attracts: "Birds",
    maintenance: "Low",
    deer_resistance: "A",
    deer_resistance_note: "Rarely damaged"
  },

  "franky boy oriental arborvitae": {
    id: "local_franky_boy",
    name: "Franky Boy Arborvitae",
    scientific_name: "Platycladus orientalis 'Franky Boy'",
    family: "Cupressaceae",
    image: "https://images.unsplash.com/photo-1598256989800-fe5f95da9787?w=400",
    description: "Dwarf evergreen with vertical fan-like foliage sprays. Compact rounded form with bright green color.",
    type: "Shrub",
    cycle: "Perennial",
    watering: "Average",
    sunlight: "Full sun",
    care_level: "Low",
    growth_rate: "Slow",
    flowering_season: "None",
    attracts: "Birds",
    maintenance: "Low",
    deer_resistance: "B",
    deer_resistance_note: "Seldom severely damaged"
  }
};

// Function to search the local database
export function searchLocalPlants(query) {
  const searchTerm = query.toLowerCase().trim();
  const results = [];

  for (const [key, plant] of Object.entries(plantDatabase)) {
    if (
      key.includes(searchTerm) ||
      plant.name.toLowerCase().includes(searchTerm) ||
      plant.scientific_name.toLowerCase().includes(searchTerm)
    ) {
      results.push(plant);
    }
  }

  return results;
}

// Function to get a plant by name (handles case and plurals)
export function getPlantByName(plantName) {
  const searchTerm = plantName.toLowerCase().trim();
  
  // Try exact match first
  if (plantDatabase[searchTerm]) {
    return plantDatabase[searchTerm];
  }
  
  // Try removing 's' or 'es' for plurals
  const singular1 = searchTerm.endsWith('s') ? searchTerm.slice(0, -1) : searchTerm;
  if (plantDatabase[singular1]) {
    return plantDatabase[singular1];
  }
  
  const singular2 = searchTerm.endsWith('es') ? searchTerm.slice(0, -2) : searchTerm;
  if (plantDatabase[singular2]) {
    return plantDatabase[singular2];
  }
  
  // Try partial match
  for (const [key, plant] of Object.entries(plantDatabase)) {
    if (key.includes(searchTerm) || searchTerm.includes(key)) {
      return plant;
    }
  }
  
  return null;
}